jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build
          command: npm build
      - persist_to_workspace:
          root: /
          paths:
            - FRONT-END

  test:
    docker:
      - image: circleci/node:14
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Debug - List Workspace Contents
          command: ls -R FRONT-END
      - run:
          name: Run Tests
          command: npm test -- FRONT-END/src/GetStarted.test.js

