version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd FRONT-END
            npm install
      - run:                
          name: Build
          command: |
              cd FRONT-END
              npm build
      - run :
          name: Run code 
          command : 
              cd FRONT-END
              npm start
      # - persist_to_workspace:
      #     root: /
      #     paths:
      #       - .circleci