version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Debug - List Contents Before Build
          command: ls -R
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build
          command: npm build
      - persist_to_workspace:
          root: /
          paths:
            - AtomSridurga/FRONT-END
            - .circleci