jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build
          command: npm build
      - persist_to_workspace:
          root: /
          paths:
            - AtomSridurga/FRONT-END

  test:
    docker:
      - image: circleci/node:14
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Run Tests
          command: npm test -- AtomSridurga/FRONT-END/src/GetStarted.test.js AtomSridurga/FRONT-END/src/DoctorLogin.test.js AtomSridurga/FRONT-END/src/Register.test.js

